### ISSUE TITLE
Zoom into certain coordinates on button click.

### ISSUE THREAD

**Issue by cerberusv2px** [mapbox/react-native-mapbox-gl#1482]
How to zoom into certain coordinates.
Suppose I am at zoom level 12 with coordinates [a1,b1]. Now on button click, I want to zoom into coordinates [a2,b2] with zoom level 20.

I did the following, but it wont work.

```
this.map.moveTo([85.4279593, 27.7159906]);
this.map.zoomTo(18);
```

**Comment by kristfal** [comment]
Use [setCamera](https://github.com/mapbox/react-native-mapbox-gl/blob/master/docs/MapView.md#setcameraconfig) instead. This function takes both coordinates and zoom level and other params.
