### ISSUE TITLE
Error: 'React/RCTBridge.h' file not found

### ISSUE THREAD

**Issue by nlshuynguyen** [mapbox/react-native-mapbox-gl#1661]
install mapbox following steps in https://github.com/react-native-mapbox-gl/maps/blob/master/ios/install.md.
But when I run it show error
![image](https://user-images.githubusercontent.com/53550422/65037525-1b5ea080-d978-11e9-8060-9591b1981697.png)

Then I go to file -> workspace setting -> legacy build system. It show another error
image
![image](https://user-images.githubusercontent.com/53550422/65037534-21548180-d978-11e9-8f08-8e1b4c519d6f.png)

How can I fix it?
` "react-native": "0.60.5"`

**Comment by kristfal** [comment]
This repo is deprecated. Use the new one for RN60+ support. See main readme.

**Comment by nlshuynguyen** [comment]
I'm sorry. This you mean I should follow steps in this link: https://github.com/nitaliano/react-native-mapbox-gl/blob/master/ios/install.md ?

**Comment by kristfal** [comment]
No. I mean using this instead:

https://github.com/react-native-mapbox-gl/maps

**Comment by nlshuynguyen** [comment]
oh. Maybe I misunderstood you. Can you show me the new one for RN60+ ?. I read in readme and can't see the link for new version. Thank you for your help.

**Comment by kristfal** [comment]
I literally posted the link to the new repo with RN60 support in the previous message. If this is not clear, then I can’t help you any further I’m afraid.

**Comment by nlshuynguyen** [comment]
yes. I tried both. but still got same error. I already created same issues in https://github.com/react-native-mapbox-gl/maps but not find solution for this.
