### ISSUE TITLE
iOS crash with MultilineString with geometries

### ISSUE THREAD

**Issue by ansarikhurshid786** [mapbox/react-native-mapbox-gl#1679]
Drawing line in map using data multinestring data from web service. Getting data like : 
```
{
  "type": "FeatureCollection",
  "totalFeatures": 1,
  "features": [
    {
      "type": "Feature",
      "id": "streets.fid--54d835f0_170f233714b_-42f7",
      "geometry": {
        "type": "GeometryCollection",
        "geometries": [
          {
            "type": "MultiLineString",
            "coordinates": [
              [
                [54.37577522, 24.46179556],
                [54.37567198,  24.46167702],
                [54.37560638, 24.46162656],
                [54.375445,24.46148218]
              ],
              [
                [54.37559877,24.46141407],
                [54.37560356,24.46141777],
                [54.37565904,24.46146109]
             ]
        ]
    }
}]}; 
```

Data is something like this working fine in android and crashing in ios. 

anyone facing same issue? 

cc: @nitaliano

**Comment by ansarikhurshid786** [comment]
@nitaliano please check my issue. i am waiting for your response.

**Comment by jaltin** [comment]
This repo is deprecated **since a long time** and is not getting updated any more, as is outlined in the readme of this repository.

Please use the new one located at [https://github.com/react-native-mapbox-gl/maps](url).

**Comment by ansarikhurshid786** [comment]
@jaltin Thanks for response. I am using react native 0.59.10 and react-native-mapbox-gl/maps is required minimum 0.60. so can't use that library. 

Can you please check my issue and some workaround. 

iOS crashing when i am loading GeometryCollection.

**Comment by ansarikhurshid786** [comment]
@jaltin I have updated to https://github.com/react-native-mapbox-gl/maps. Now I am getting same issue. Now i am getting issue: 
`libc++abi.dylib: terminating with uncaught exception of type mapbox::util::bad_variant_access`

do you have idea. how to resolve it.

**Comment by jaltin** [comment]
@ansarikhurshid786 great to hear that you updated to the new repo.

I'm afraid I can't help you. 

I would suggest that you create a new issue in [the other repo](https://github.com/react-native-mapbox-gl/maps/issues/new?assignees=&labels=&template=bug_report.md&title=) and **make sure** to follow the submission instructions there and include all the relevant info about version used, a reproducible code example etc. Hopefully someone else will be able to help you

**Comment by ansarikhurshid786** [comment]
@jaltin thanks for your response. I already created issue in that repo got solution.
