### ISSUE TITLE
Display Map after downloaded the Packed Style from MapBox

### ISSUE THREAD

**Issue by FernandesTeu** [mapbox/react-native-mapbox-gl#1694]
Hi Guys!
I'm starting as a developer react native, and I'm trying to render an offline map.
I followed the docs and works fine, but how do I display the style that was downloaded in my application? 

Thank you masters!

![image](https://user-images.githubusercontent.com/51789880/94966636-fe8a0200-04d3-11eb-8911-8bf0a1072321.png)

**Comment by sabarikobagapau** [comment]
Hi @FernandesTeu  are you achive it display the downloaded map plz help
